// Auto-generated Ring extension
// Generated by parsec.ring
// Do not edit manually

#![allow(non_snake_case)]
#![allow(unused_variables)]
#![allow(unused_imports)]

use ring_lang_rs::*;
use std::ffi::c_void;

use chrono::{DateTime, Utc, Local, NaiveDateTime, NaiveDate, NaiveTime, Duration, Datelike, Timelike, Weekday};
use chrono::format::ParseError;

// ============================================
// Current Time
// ============================================

/// Get current UTC timestamp (RFC 3339 format)
pub fn now_utc() -> String {
    Utc::now().to_rfc3339()
}

/// Get current local timestamp (RFC 3339 format)
pub fn now_local() -> String {
    Local::now().to_rfc3339()
}

/// Get current Unix timestamp (seconds since epoch)
pub fn now_unix() -> i64 {
    Utc::now().timestamp()
}

/// Get current Unix timestamp in milliseconds
pub fn now_unix_ms() -> i64 {
    Utc::now().timestamp_millis()
}

// ============================================
// Parsing
// ============================================

/// Parse RFC 3339 datetime string (e.g., "2024-01-15T10:30:00Z")
pub fn parse_rfc3339(s: &str) -> String {
    DateTime::parse_from_rfc3339(s)
        .map(|dt| dt.to_rfc3339())
        .unwrap_or_else(|e| format!("error: {}", e))
}

/// Parse datetime with custom format
/// Common formats: "%Y-%m-%d %H:%M:%S", "%d/%m/%Y", "%Y-%m-%d"
pub fn parse_format(s: &str, format: &str) -> String {
    NaiveDateTime::parse_from_str(s, format)
        .map(|dt| dt.format("%Y-%m-%dT%H:%M:%S").to_string())
        .unwrap_or_else(|e| format!("error: {}", e))
}

/// Parse date only (returns "YYYY-MM-DD")
pub fn parse_date(s: &str, format: &str) -> String {
    NaiveDate::parse_from_str(s, format)
        .map(|d| d.format("%Y-%m-%d").to_string())
        .unwrap_or_else(|e| format!("error: {}", e))
}

/// Parse Unix timestamp to RFC 3339
pub fn from_unix(timestamp: i64) -> String {
    DateTime::from_timestamp(timestamp, 0)
        .map(|dt| dt.to_rfc3339())
        .unwrap_or_else(|| "error: invalid timestamp".to_string())
}

/// Parse Unix timestamp in milliseconds to RFC 3339
pub fn from_unix_ms(timestamp_ms: i64) -> String {
    DateTime::from_timestamp_millis(timestamp_ms)
        .map(|dt| dt.to_rfc3339())
        .unwrap_or_else(|| "error: invalid timestamp".to_string())
}

// ============================================
// Formatting
// ============================================

/// Format datetime with custom format string
pub fn format_datetime(datetime: &str, format: &str) -> String {
    parse_any_datetime(datetime)
        .map(|dt| dt.format(format).to_string())
        .unwrap_or_else(|| "error: invalid datetime".to_string())
}

/// Convert to RFC 3339 format
pub fn to_rfc3339(datetime: &str) -> String {
    parse_any_datetime(datetime)
        .map(|dt| DateTime::<Utc>::from_naive_utc_and_offset(dt, Utc).to_rfc3339())
        .unwrap_or_else(|| "error: invalid datetime".to_string())
}

/// Convert to RFC 2822 format (email date format)
pub fn to_rfc2822(datetime: &str) -> String {
    parse_any_datetime(datetime)
        .map(|dt| DateTime::<Utc>::from_naive_utc_and_offset(dt, Utc).to_rfc2822())
        .unwrap_or_else(|| "error: invalid datetime".to_string())
}

/// Convert to Unix timestamp
pub fn to_unix(datetime: &str) -> i64 {
    parse_any_datetime(datetime)
        .map(|dt| DateTime::<Utc>::from_naive_utc_and_offset(dt, Utc).timestamp())
        .unwrap_or(0)
}

// ============================================
// Components Extraction
// ============================================

/// Get year from datetime
pub fn get_year(datetime: &str) -> i32 {
    parse_any_datetime(datetime).map(|dt| dt.year()).unwrap_or(0)
}

/// Get month (1-12) from datetime
pub fn get_month(datetime: &str) -> u32 {
    parse_any_datetime(datetime).map(|dt| dt.month()).unwrap_or(0)
}

/// Get day of month (1-31) from datetime
pub fn get_day(datetime: &str) -> u32 {
    parse_any_datetime(datetime).map(|dt| dt.day()).unwrap_or(0)
}

/// Get hour (0-23) from datetime
pub fn get_hour(datetime: &str) -> u32 {
    parse_any_datetime(datetime).map(|dt| dt.hour()).unwrap_or(0)
}

/// Get minute (0-59) from datetime
pub fn get_minute(datetime: &str) -> u32 {
    parse_any_datetime(datetime).map(|dt| dt.minute()).unwrap_or(0)
}

/// Get second (0-59) from datetime
pub fn get_second(datetime: &str) -> u32 {
    parse_any_datetime(datetime).map(|dt| dt.second()).unwrap_or(0)
}

/// Get day of week (1=Monday, 7=Sunday)
pub fn get_weekday(datetime: &str) -> u32 {
    parse_any_datetime(datetime)
        .map(|dt| dt.weekday().num_days_from_monday() + 1)
        .unwrap_or(0)
}

/// Get day of week name
pub fn get_weekday_name(datetime: &str) -> String {
    parse_any_datetime(datetime)
        .map(|dt| dt.format("%A").to_string())
        .unwrap_or_default()
}

/// Get day of year (1-366)
pub fn get_day_of_year(datetime: &str) -> u32 {
    parse_any_datetime(datetime).map(|dt| dt.ordinal()).unwrap_or(0)
}

/// Get ISO week number (1-53)
pub fn get_week_number(datetime: &str) -> u32 {
    parse_any_datetime(datetime).map(|dt| dt.iso_week().week()).unwrap_or(0)
}

// ============================================
// Date Arithmetic
// ============================================

/// Add days to datetime
pub fn add_days(datetime: &str, days: i64) -> String {
    parse_any_datetime(datetime)
        .and_then(|dt| dt.checked_add_signed(Duration::days(days)))
        .map(|dt| DateTime::<Utc>::from_naive_utc_and_offset(dt, Utc).to_rfc3339())
        .unwrap_or_else(|| "error: invalid operation".to_string())
}

/// Add hours to datetime
pub fn add_hours(datetime: &str, hours: i64) -> String {
    parse_any_datetime(datetime)
        .and_then(|dt| dt.checked_add_signed(Duration::hours(hours)))
        .map(|dt| DateTime::<Utc>::from_naive_utc_and_offset(dt, Utc).to_rfc3339())
        .unwrap_or_else(|| "error: invalid operation".to_string())
}

/// Add minutes to datetime
pub fn add_minutes(datetime: &str, minutes: i64) -> String {
    parse_any_datetime(datetime)
        .and_then(|dt| dt.checked_add_signed(Duration::minutes(minutes)))
        .map(|dt| DateTime::<Utc>::from_naive_utc_and_offset(dt, Utc).to_rfc3339())
        .unwrap_or_else(|| "error: invalid operation".to_string())
}

/// Add seconds to datetime
pub fn add_seconds(datetime: &str, seconds: i64) -> String {
    parse_any_datetime(datetime)
        .and_then(|dt| dt.checked_add_signed(Duration::seconds(seconds)))
        .map(|dt| DateTime::<Utc>::from_naive_utc_and_offset(dt, Utc).to_rfc3339())
        .unwrap_or_else(|| "error: invalid operation".to_string())
}

/// Add weeks to datetime
pub fn add_weeks(datetime: &str, weeks: i64) -> String {
    parse_any_datetime(datetime)
        .and_then(|dt| dt.checked_add_signed(Duration::weeks(weeks)))
        .map(|dt| DateTime::<Utc>::from_naive_utc_and_offset(dt, Utc).to_rfc3339())
        .unwrap_or_else(|| "error: invalid operation".to_string())
}

/// Add months to datetime (handles month boundaries)
pub fn add_months(datetime: &str, months: i32) -> String {
    parse_any_datetime(datetime)
        .and_then(|dt| {
            let date = dt.date();
            let new_date = if months >= 0 {
                date.checked_add_months(chrono::Months::new(months as u32))
            } else {
                date.checked_sub_months(chrono::Months::new((-months) as u32))
            };
            new_date.map(|d| d.and_time(dt.time()))
        })
        .map(|dt| DateTime::<Utc>::from_naive_utc_and_offset(dt, Utc).to_rfc3339())
        .unwrap_or_else(|| "error: invalid operation".to_string())
}

/// Add years to datetime
pub fn add_years(datetime: &str, years: i32) -> String {
    add_months(datetime, years * 12)
}

// ============================================
// Date Comparison
// ============================================

/// Get difference between two datetimes in days
pub fn diff_days(datetime1: &str, datetime2: &str) -> i64 {
    match (parse_any_datetime(datetime1), parse_any_datetime(datetime2)) {
        (Some(dt1), Some(dt2)) => (dt1 - dt2).num_days(),
        _ => 0,
    }
}

/// Get difference between two datetimes in hours
pub fn diff_hours(datetime1: &str, datetime2: &str) -> i64 {
    match (parse_any_datetime(datetime1), parse_any_datetime(datetime2)) {
        (Some(dt1), Some(dt2)) => (dt1 - dt2).num_hours(),
        _ => 0,
    }
}

/// Get difference between two datetimes in minutes
pub fn diff_minutes(datetime1: &str, datetime2: &str) -> i64 {
    match (parse_any_datetime(datetime1), parse_any_datetime(datetime2)) {
        (Some(dt1), Some(dt2)) => (dt1 - dt2).num_minutes(),
        _ => 0,
    }
}

/// Get difference between two datetimes in seconds
pub fn diff_seconds(datetime1: &str, datetime2: &str) -> i64 {
    match (parse_any_datetime(datetime1), parse_any_datetime(datetime2)) {
        (Some(dt1), Some(dt2)) => (dt1 - dt2).num_seconds(),
        _ => 0,
    }
}

/// Check if datetime1 is before datetime2
pub fn is_before(datetime1: &str, datetime2: &str) -> bool {
    match (parse_any_datetime(datetime1), parse_any_datetime(datetime2)) {
        (Some(dt1), Some(dt2)) => dt1 < dt2,
        _ => false,
    }
}

/// Check if datetime1 is after datetime2
pub fn is_after(datetime1: &str, datetime2: &str) -> bool {
    match (parse_any_datetime(datetime1), parse_any_datetime(datetime2)) {
        (Some(dt1), Some(dt2)) => dt1 > dt2,
        _ => false,
    }
}

/// Check if two datetimes are the same day
pub fn is_same_day(datetime1: &str, datetime2: &str) -> bool {
    match (parse_any_datetime(datetime1), parse_any_datetime(datetime2)) {
        (Some(dt1), Some(dt2)) => dt1.date() == dt2.date(),
        _ => false,
    }
}

// ============================================
// Date Construction
// ============================================

/// Create datetime from components
pub fn create(year: i32, month: u32, day: u32, hour: u32, minute: u32, second: u32) -> String {
    NaiveDate::from_ymd_opt(year, month, day)
        .and_then(|d| d.and_hms_opt(hour, minute, second))
        .map(|dt| DateTime::<Utc>::from_naive_utc_and_offset(dt, Utc).to_rfc3339())
        .unwrap_or_else(|| "error: invalid date components".to_string())
}

/// Create date only
pub fn create_date(year: i32, month: u32, day: u32) -> String {
    NaiveDate::from_ymd_opt(year, month, day)
        .map(|d| d.format("%Y-%m-%d").to_string())
        .unwrap_or_else(|| "error: invalid date components".to_string())
}

/// Get start of day (00:00:00)
pub fn start_of_day(datetime: &str) -> String {
    parse_any_datetime(datetime)
        .map(|dt| dt.date().and_hms_opt(0, 0, 0).unwrap())
        .map(|dt| DateTime::<Utc>::from_naive_utc_and_offset(dt, Utc).to_rfc3339())
        .unwrap_or_else(|| "error: invalid datetime".to_string())
}

/// Get end of day (23:59:59)
pub fn end_of_day(datetime: &str) -> String {
    parse_any_datetime(datetime)
        .map(|dt| dt.date().and_hms_opt(23, 59, 59).unwrap())
        .map(|dt| DateTime::<Utc>::from_naive_utc_and_offset(dt, Utc).to_rfc3339())
        .unwrap_or_else(|| "error: invalid datetime".to_string())
}

// ============================================
// Validation
// ============================================

/// Check if string is valid datetime
pub fn is_valid(datetime: &str) -> bool {
    parse_any_datetime(datetime).is_some()
}

/// Check if year is leap year
pub fn is_leap_year(year: i32) -> bool {
    NaiveDate::from_ymd_opt(year, 2, 29).is_some()
}

/// Get days in month
pub fn days_in_month(year: i32, month: u32) -> u32 {
    if month == 12 {
        NaiveDate::from_ymd_opt(year + 1, 1, 1)
    } else {
        NaiveDate::from_ymd_opt(year, month + 1, 1)
    }
    .and_then(|d| d.pred_opt())
    .map(|d| d.day())
    .unwrap_or(0)
}

// ============================================
// Helper Functions (not exposed)
// ============================================

fn parse_any_datetime(s: &str) -> Option<NaiveDateTime> {
    // Try RFC 3339 first
    if let Ok(dt) = DateTime::parse_from_rfc3339(s) {
        return Some(dt.naive_utc());
    }
    
    // Try common formats
    let formats = [
        "%Y-%m-%dT%H:%M:%S",
        "%Y-%m-%d %H:%M:%S",
        "%Y-%m-%d",
        "%d/%m/%Y %H:%M:%S",
        "%d/%m/%Y",
        "%m/%d/%Y %H:%M:%S",
        "%m/%d/%Y",
    ];
    
    for format in formats {
        if let Ok(dt) = NaiveDateTime::parse_from_str(s, format) {
            return Some(dt);
        }
        if let Ok(d) = NaiveDate::parse_from_str(s, format) {
            return Some(d.and_hms_opt(0, 0, 0).unwrap());
        }
    }
    
    None
}

// ============================================
// Function: now_utc
// ============================================
ring_func!(ring_dt_now_utc, |p| {
    ring_check_paracount!(p, 0);


    let __result = now_utc();
    ring_ret_string!(p, &__result);
});

// ============================================
// Function: now_local
// ============================================
ring_func!(ring_dt_now_local, |p| {
    ring_check_paracount!(p, 0);


    let __result = now_local();
    ring_ret_string!(p, &__result);
});

// ============================================
// Function: now_unix
// ============================================
ring_func!(ring_dt_now_unix, |p| {
    ring_check_paracount!(p, 0);


    let __result = now_unix();
    ring_ret_number!(p, __result as f64);
});

// ============================================
// Function: now_unix_ms
// ============================================
ring_func!(ring_dt_now_unix_ms, |p| {
    ring_check_paracount!(p, 0);


    let __result = now_unix_ms();
    ring_ret_number!(p, __result as f64);
});

// ============================================
// Function: parse_rfc3339
// ============================================
ring_func!(ring_dt_parse_rfc3339, |p| {
    ring_check_paracount!(p, 1);
    ring_check_string!(p, 1);

    let __arg_1 = ring_get_string!(p, 1);

    let __result = parse_rfc3339(__arg_1);
    ring_ret_string!(p, &__result);
});

// ============================================
// Function: parse_format
// ============================================
ring_func!(ring_dt_parse_format, |p| {
    ring_check_paracount!(p, 2);
    ring_check_string!(p, 1);
    ring_check_string!(p, 2);

    let __arg_1 = ring_get_string!(p, 1);
    let __arg_2 = ring_get_string!(p, 2);

    let __result = parse_format(__arg_1, __arg_2);
    ring_ret_string!(p, &__result);
});

// ============================================
// Function: parse_date
// ============================================
ring_func!(ring_dt_parse_date, |p| {
    ring_check_paracount!(p, 2);
    ring_check_string!(p, 1);
    ring_check_string!(p, 2);

    let __arg_1 = ring_get_string!(p, 1);
    let __arg_2 = ring_get_string!(p, 2);

    let __result = parse_date(__arg_1, __arg_2);
    ring_ret_string!(p, &__result);
});

// ============================================
// Function: from_unix
// ============================================
ring_func!(ring_dt_from_unix, |p| {
    ring_check_paracount!(p, 1);
    ring_check_number!(p, 1);

    let __arg_1 = ring_get_number!(p, 1) as i64;

    let __result = from_unix(__arg_1);
    ring_ret_string!(p, &__result);
});

// ============================================
// Function: from_unix_ms
// ============================================
ring_func!(ring_dt_from_unix_ms, |p| {
    ring_check_paracount!(p, 1);
    ring_check_number!(p, 1);

    let __arg_1 = ring_get_number!(p, 1) as i64;

    let __result = from_unix_ms(__arg_1);
    ring_ret_string!(p, &__result);
});

// ============================================
// Function: format_datetime
// ============================================
ring_func!(ring_dt_format_datetime, |p| {
    ring_check_paracount!(p, 2);
    ring_check_string!(p, 1);
    ring_check_string!(p, 2);

    let __arg_1 = ring_get_string!(p, 1);
    let __arg_2 = ring_get_string!(p, 2);

    let __result = format_datetime(__arg_1, __arg_2);
    ring_ret_string!(p, &__result);
});

// ============================================
// Function: to_rfc3339
// ============================================
ring_func!(ring_dt_to_rfc3339, |p| {
    ring_check_paracount!(p, 1);
    ring_check_string!(p, 1);

    let __arg_1 = ring_get_string!(p, 1);

    let __result = to_rfc3339(__arg_1);
    ring_ret_string!(p, &__result);
});

// ============================================
// Function: to_rfc2822
// ============================================
ring_func!(ring_dt_to_rfc2822, |p| {
    ring_check_paracount!(p, 1);
    ring_check_string!(p, 1);

    let __arg_1 = ring_get_string!(p, 1);

    let __result = to_rfc2822(__arg_1);
    ring_ret_string!(p, &__result);
});

// ============================================
// Function: to_unix
// ============================================
ring_func!(ring_dt_to_unix, |p| {
    ring_check_paracount!(p, 1);
    ring_check_string!(p, 1);

    let __arg_1 = ring_get_string!(p, 1);

    let __result = to_unix(__arg_1);
    ring_ret_number!(p, __result as f64);
});

// ============================================
// Function: get_year
// ============================================
ring_func!(ring_dt_get_year, |p| {
    ring_check_paracount!(p, 1);
    ring_check_string!(p, 1);

    let __arg_1 = ring_get_string!(p, 1);

    let __result = get_year(__arg_1);
    ring_ret_number!(p, __result as f64);
});

// ============================================
// Function: get_month
// ============================================
ring_func!(ring_dt_get_month, |p| {
    ring_check_paracount!(p, 1);
    ring_check_string!(p, 1);

    let __arg_1 = ring_get_string!(p, 1);

    let __result = get_month(__arg_1);
    ring_ret_number!(p, __result as f64);
});

// ============================================
// Function: get_day
// ============================================
ring_func!(ring_dt_get_day, |p| {
    ring_check_paracount!(p, 1);
    ring_check_string!(p, 1);

    let __arg_1 = ring_get_string!(p, 1);

    let __result = get_day(__arg_1);
    ring_ret_number!(p, __result as f64);
});

// ============================================
// Function: get_hour
// ============================================
ring_func!(ring_dt_get_hour, |p| {
    ring_check_paracount!(p, 1);
    ring_check_string!(p, 1);

    let __arg_1 = ring_get_string!(p, 1);

    let __result = get_hour(__arg_1);
    ring_ret_number!(p, __result as f64);
});

// ============================================
// Function: get_minute
// ============================================
ring_func!(ring_dt_get_minute, |p| {
    ring_check_paracount!(p, 1);
    ring_check_string!(p, 1);

    let __arg_1 = ring_get_string!(p, 1);

    let __result = get_minute(__arg_1);
    ring_ret_number!(p, __result as f64);
});

// ============================================
// Function: get_second
// ============================================
ring_func!(ring_dt_get_second, |p| {
    ring_check_paracount!(p, 1);
    ring_check_string!(p, 1);

    let __arg_1 = ring_get_string!(p, 1);

    let __result = get_second(__arg_1);
    ring_ret_number!(p, __result as f64);
});

// ============================================
// Function: get_weekday
// ============================================
ring_func!(ring_dt_get_weekday, |p| {
    ring_check_paracount!(p, 1);
    ring_check_string!(p, 1);

    let __arg_1 = ring_get_string!(p, 1);

    let __result = get_weekday(__arg_1);
    ring_ret_number!(p, __result as f64);
});

// ============================================
// Function: get_weekday_name
// ============================================
ring_func!(ring_dt_get_weekday_name, |p| {
    ring_check_paracount!(p, 1);
    ring_check_string!(p, 1);

    let __arg_1 = ring_get_string!(p, 1);

    let __result = get_weekday_name(__arg_1);
    ring_ret_string!(p, &__result);
});

// ============================================
// Function: get_day_of_year
// ============================================
ring_func!(ring_dt_get_day_of_year, |p| {
    ring_check_paracount!(p, 1);
    ring_check_string!(p, 1);

    let __arg_1 = ring_get_string!(p, 1);

    let __result = get_day_of_year(__arg_1);
    ring_ret_number!(p, __result as f64);
});

// ============================================
// Function: get_week_number
// ============================================
ring_func!(ring_dt_get_week_number, |p| {
    ring_check_paracount!(p, 1);
    ring_check_string!(p, 1);

    let __arg_1 = ring_get_string!(p, 1);

    let __result = get_week_number(__arg_1);
    ring_ret_number!(p, __result as f64);
});

// ============================================
// Function: add_days
// ============================================
ring_func!(ring_dt_add_days, |p| {
    ring_check_paracount!(p, 2);
    ring_check_string!(p, 1);
    ring_check_number!(p, 2);

    let __arg_1 = ring_get_string!(p, 1);
    let __arg_2 = ring_get_number!(p, 2) as i64;

    let __result = add_days(__arg_1, __arg_2);
    ring_ret_string!(p, &__result);
});

// ============================================
// Function: add_hours
// ============================================
ring_func!(ring_dt_add_hours, |p| {
    ring_check_paracount!(p, 2);
    ring_check_string!(p, 1);
    ring_check_number!(p, 2);

    let __arg_1 = ring_get_string!(p, 1);
    let __arg_2 = ring_get_number!(p, 2) as i64;

    let __result = add_hours(__arg_1, __arg_2);
    ring_ret_string!(p, &__result);
});

// ============================================
// Function: add_minutes
// ============================================
ring_func!(ring_dt_add_minutes, |p| {
    ring_check_paracount!(p, 2);
    ring_check_string!(p, 1);
    ring_check_number!(p, 2);

    let __arg_1 = ring_get_string!(p, 1);
    let __arg_2 = ring_get_number!(p, 2) as i64;

    let __result = add_minutes(__arg_1, __arg_2);
    ring_ret_string!(p, &__result);
});

// ============================================
// Function: add_seconds
// ============================================
ring_func!(ring_dt_add_seconds, |p| {
    ring_check_paracount!(p, 2);
    ring_check_string!(p, 1);
    ring_check_number!(p, 2);

    let __arg_1 = ring_get_string!(p, 1);
    let __arg_2 = ring_get_number!(p, 2) as i64;

    let __result = add_seconds(__arg_1, __arg_2);
    ring_ret_string!(p, &__result);
});

// ============================================
// Function: add_weeks
// ============================================
ring_func!(ring_dt_add_weeks, |p| {
    ring_check_paracount!(p, 2);
    ring_check_string!(p, 1);
    ring_check_number!(p, 2);

    let __arg_1 = ring_get_string!(p, 1);
    let __arg_2 = ring_get_number!(p, 2) as i64;

    let __result = add_weeks(__arg_1, __arg_2);
    ring_ret_string!(p, &__result);
});

// ============================================
// Function: add_months
// ============================================
ring_func!(ring_dt_add_months, |p| {
    ring_check_paracount!(p, 2);
    ring_check_string!(p, 1);
    ring_check_number!(p, 2);

    let __arg_1 = ring_get_string!(p, 1);
    let __arg_2 = ring_get_number!(p, 2) as i32;

    let __result = add_months(__arg_1, __arg_2);
    ring_ret_string!(p, &__result);
});

// ============================================
// Function: add_years
// ============================================
ring_func!(ring_dt_add_years, |p| {
    ring_check_paracount!(p, 2);
    ring_check_string!(p, 1);
    ring_check_number!(p, 2);

    let __arg_1 = ring_get_string!(p, 1);
    let __arg_2 = ring_get_number!(p, 2) as i32;

    let __result = add_years(__arg_1, __arg_2);
    ring_ret_string!(p, &__result);
});

// ============================================
// Function: diff_days
// ============================================
ring_func!(ring_dt_diff_days, |p| {
    ring_check_paracount!(p, 2);
    ring_check_string!(p, 1);
    ring_check_string!(p, 2);

    let __arg_1 = ring_get_string!(p, 1);
    let __arg_2 = ring_get_string!(p, 2);

    let __result = diff_days(__arg_1, __arg_2);
    ring_ret_number!(p, __result as f64);
});

// ============================================
// Function: diff_hours
// ============================================
ring_func!(ring_dt_diff_hours, |p| {
    ring_check_paracount!(p, 2);
    ring_check_string!(p, 1);
    ring_check_string!(p, 2);

    let __arg_1 = ring_get_string!(p, 1);
    let __arg_2 = ring_get_string!(p, 2);

    let __result = diff_hours(__arg_1, __arg_2);
    ring_ret_number!(p, __result as f64);
});

// ============================================
// Function: diff_minutes
// ============================================
ring_func!(ring_dt_diff_minutes, |p| {
    ring_check_paracount!(p, 2);
    ring_check_string!(p, 1);
    ring_check_string!(p, 2);

    let __arg_1 = ring_get_string!(p, 1);
    let __arg_2 = ring_get_string!(p, 2);

    let __result = diff_minutes(__arg_1, __arg_2);
    ring_ret_number!(p, __result as f64);
});

// ============================================
// Function: diff_seconds
// ============================================
ring_func!(ring_dt_diff_seconds, |p| {
    ring_check_paracount!(p, 2);
    ring_check_string!(p, 1);
    ring_check_string!(p, 2);

    let __arg_1 = ring_get_string!(p, 1);
    let __arg_2 = ring_get_string!(p, 2);

    let __result = diff_seconds(__arg_1, __arg_2);
    ring_ret_number!(p, __result as f64);
});

// ============================================
// Function: is_before
// ============================================
ring_func!(ring_dt_is_before, |p| {
    ring_check_paracount!(p, 2);
    ring_check_string!(p, 1);
    ring_check_string!(p, 2);

    let __arg_1 = ring_get_string!(p, 1);
    let __arg_2 = ring_get_string!(p, 2);

    let __result = is_before(__arg_1, __arg_2);
    ring_ret_number!(p, if __result { 1.0 } else { 0.0 });
});

// ============================================
// Function: is_after
// ============================================
ring_func!(ring_dt_is_after, |p| {
    ring_check_paracount!(p, 2);
    ring_check_string!(p, 1);
    ring_check_string!(p, 2);

    let __arg_1 = ring_get_string!(p, 1);
    let __arg_2 = ring_get_string!(p, 2);

    let __result = is_after(__arg_1, __arg_2);
    ring_ret_number!(p, if __result { 1.0 } else { 0.0 });
});

// ============================================
// Function: is_same_day
// ============================================
ring_func!(ring_dt_is_same_day, |p| {
    ring_check_paracount!(p, 2);
    ring_check_string!(p, 1);
    ring_check_string!(p, 2);

    let __arg_1 = ring_get_string!(p, 1);
    let __arg_2 = ring_get_string!(p, 2);

    let __result = is_same_day(__arg_1, __arg_2);
    ring_ret_number!(p, if __result { 1.0 } else { 0.0 });
});

// ============================================
// Function: create
// ============================================
ring_func!(ring_dt_create, |p| {
    ring_check_paracount!(p, 6);
    ring_check_number!(p, 1);
    ring_check_number!(p, 2);
    ring_check_number!(p, 3);
    ring_check_number!(p, 4);
    ring_check_number!(p, 5);
    ring_check_number!(p, 6);

    let __arg_1 = ring_get_number!(p, 1) as i32;
    let __arg_2 = ring_get_number!(p, 2) as u32;
    let __arg_3 = ring_get_number!(p, 3) as u32;
    let __arg_4 = ring_get_number!(p, 4) as u32;
    let __arg_5 = ring_get_number!(p, 5) as u32;
    let __arg_6 = ring_get_number!(p, 6) as u32;

    let __result = create(__arg_1, __arg_2, __arg_3, __arg_4, __arg_5, __arg_6);
    ring_ret_string!(p, &__result);
});

// ============================================
// Function: create_date
// ============================================
ring_func!(ring_dt_create_date, |p| {
    ring_check_paracount!(p, 3);
    ring_check_number!(p, 1);
    ring_check_number!(p, 2);
    ring_check_number!(p, 3);

    let __arg_1 = ring_get_number!(p, 1) as i32;
    let __arg_2 = ring_get_number!(p, 2) as u32;
    let __arg_3 = ring_get_number!(p, 3) as u32;

    let __result = create_date(__arg_1, __arg_2, __arg_3);
    ring_ret_string!(p, &__result);
});

// ============================================
// Function: start_of_day
// ============================================
ring_func!(ring_dt_start_of_day, |p| {
    ring_check_paracount!(p, 1);
    ring_check_string!(p, 1);

    let __arg_1 = ring_get_string!(p, 1);

    let __result = start_of_day(__arg_1);
    ring_ret_string!(p, &__result);
});

// ============================================
// Function: end_of_day
// ============================================
ring_func!(ring_dt_end_of_day, |p| {
    ring_check_paracount!(p, 1);
    ring_check_string!(p, 1);

    let __arg_1 = ring_get_string!(p, 1);

    let __result = end_of_day(__arg_1);
    ring_ret_string!(p, &__result);
});

// ============================================
// Function: is_valid
// ============================================
ring_func!(ring_dt_is_valid, |p| {
    ring_check_paracount!(p, 1);
    ring_check_string!(p, 1);

    let __arg_1 = ring_get_string!(p, 1);

    let __result = is_valid(__arg_1);
    ring_ret_number!(p, if __result { 1.0 } else { 0.0 });
});

// ============================================
// Function: is_leap_year
// ============================================
ring_func!(ring_dt_is_leap_year, |p| {
    ring_check_paracount!(p, 1);
    ring_check_number!(p, 1);

    let __arg_1 = ring_get_number!(p, 1) as i32;

    let __result = is_leap_year(__arg_1);
    ring_ret_number!(p, if __result { 1.0 } else { 0.0 });
});

// ============================================
// Function: days_in_month
// ============================================
ring_func!(ring_dt_days_in_month, |p| {
    ring_check_paracount!(p, 2);
    ring_check_number!(p, 1);
    ring_check_number!(p, 2);

    let __arg_1 = ring_get_number!(p, 1) as i32;
    let __arg_2 = ring_get_number!(p, 2) as u32;

    let __result = days_in_month(__arg_1, __arg_2);
    ring_ret_number!(p, __result as f64);
});

// ============================================
// Library Registration
// ============================================
ring_libinit! {
    b"dt_now_utc\0" => ring_dt_now_utc,
    b"dt_now_local\0" => ring_dt_now_local,
    b"dt_now_unix\0" => ring_dt_now_unix,
    b"dt_now_unix_ms\0" => ring_dt_now_unix_ms,
    b"dt_parse_rfc3339\0" => ring_dt_parse_rfc3339,
    b"dt_parse_format\0" => ring_dt_parse_format,
    b"dt_parse_date\0" => ring_dt_parse_date,
    b"dt_from_unix\0" => ring_dt_from_unix,
    b"dt_from_unix_ms\0" => ring_dt_from_unix_ms,
    b"dt_format_datetime\0" => ring_dt_format_datetime,
    b"dt_to_rfc3339\0" => ring_dt_to_rfc3339,
    b"dt_to_rfc2822\0" => ring_dt_to_rfc2822,
    b"dt_to_unix\0" => ring_dt_to_unix,
    b"dt_get_year\0" => ring_dt_get_year,
    b"dt_get_month\0" => ring_dt_get_month,
    b"dt_get_day\0" => ring_dt_get_day,
    b"dt_get_hour\0" => ring_dt_get_hour,
    b"dt_get_minute\0" => ring_dt_get_minute,
    b"dt_get_second\0" => ring_dt_get_second,
    b"dt_get_weekday\0" => ring_dt_get_weekday,
    b"dt_get_weekday_name\0" => ring_dt_get_weekday_name,
    b"dt_get_day_of_year\0" => ring_dt_get_day_of_year,
    b"dt_get_week_number\0" => ring_dt_get_week_number,
    b"dt_add_days\0" => ring_dt_add_days,
    b"dt_add_hours\0" => ring_dt_add_hours,
    b"dt_add_minutes\0" => ring_dt_add_minutes,
    b"dt_add_seconds\0" => ring_dt_add_seconds,
    b"dt_add_weeks\0" => ring_dt_add_weeks,
    b"dt_add_months\0" => ring_dt_add_months,
    b"dt_add_years\0" => ring_dt_add_years,
    b"dt_diff_days\0" => ring_dt_diff_days,
    b"dt_diff_hours\0" => ring_dt_diff_hours,
    b"dt_diff_minutes\0" => ring_dt_diff_minutes,
    b"dt_diff_seconds\0" => ring_dt_diff_seconds,
    b"dt_is_before\0" => ring_dt_is_before,
    b"dt_is_after\0" => ring_dt_is_after,
    b"dt_is_same_day\0" => ring_dt_is_same_day,
    b"dt_create\0" => ring_dt_create,
    b"dt_create_date\0" => ring_dt_create_date,
    b"dt_start_of_day\0" => ring_dt_start_of_day,
    b"dt_end_of_day\0" => ring_dt_end_of_day,
    b"dt_is_valid\0" => ring_dt_is_valid,
    b"dt_is_leap_year\0" => ring_dt_is_leap_year,
    b"dt_days_in_month\0" => ring_dt_days_in_month
}
